const API='https://api.cloudflare.com/client/v4';
function cfg(){const account=process.env.CLOUDFLARE_ACCOUNT_ID,token=process.env.CLOUDFLARE_D1_TOKEN,db=process.env.CLOUDFLARE_D1_DATABASE_ID;if(!account||!token)throw new Error('Cloudflare D1 credentials are not configured');return{account,token,db}}
async function cf(path,method='GET',body){const {token}=cfg();const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json();if(!r.ok||j.success===false)throw new Error(j.errors?.[0]?.message||'Cloudflare D1 request failed');return j.result}
export async function ensureDatabase(){let c=cfg();if(c.db)return c.db;const list=await cf('/accounts/'+c.account+'/d1/database');let db=list?.find?.(x=>x.name==='qa-hub-jobs');if(!db)db=await cf('/accounts/'+c.account+'/d1/database','POST',{name:'qa-hub-jobs'});return db.uuid}
export async function query(sql,params=[]){const c=cfg(),db=await ensureDatabase();return cf('/accounts/'+c.account+'/d1/database/'+db+'/query','POST',{sql,params})}
export async function init(){await query(`CREATE TABLE IF NOT EXISTS artwork_jobs (id TEXT PRIMARY KEY,type TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,game_id TEXT,name TEXT,provider TEXT,tile_url TEXT,claimed_by TEXT,lease_expires INTEGER,result_json TEXT,completed_at TEXT)`)}
export async function createJob(input){await init();const id=crypto.randomUUID(),createdAt=new Date().toISOString();await query('INSERT INTO artwork_jobs (id,type,status,created_at,attempts,game_id,name,provider,tile_url) VALUES (?,?,?,?,?,?,?,?,?)',[id,'artwork_detection','QUEUED',createdAt,0,input.gameId||'',input.name||'',input.provider||'',input.tileUrl]);return{id,type:'artwork_detection',status:'QUEUED',createdAt,attempts:0,...input}}
function row(r){if(!r)return null;return{id:r.id,type:r.type,status:r.status,createdAt:r.created_at,attempts:r.attempts,gameId:r.game_id,name:r.name,provider:r.provider,tileUrl:r.tile_url,claimedBy:r.claimed_by,leaseExpires:r.lease_expires,result:r.result_json?JSON.parse(r.result_json):undefined,completedAt:r.completed_at}}
export async function getJob(id){await init();const q=await query('SELECT * FROM artwork_jobs WHERE id=? LIMIT 1',[id]);return row(q?.[0]?.results?.[0])}
export async function claim(workerId){await init();const now=Date.now(),lease=now+120000;const q=await query("SELECT * FROM artwork_jobs WHERE type='artwork_detection' AND (status='QUEUED' OR (status='CLAIMED' AND lease_expires<?)) ORDER BY created_at LIMIT 1",[now]);const j=q?.[0]?.results?.[0];if(!j)return null;await query("UPDATE artwork_jobs SET status='CLAIMED',claimed_by=?,lease_expires=?,attempts=attempts+1 WHERE id=? AND (status='QUEUED' OR lease_expires<?)",[workerId,lease,j.id,now]);return getJob(j.id)}
export async function complete(id,workerId,result){await init();const completedAt=new Date().toISOString();const q=await query("UPDATE artwork_jobs SET status='DONE',result_json=?,completed_at=?,lease_expires=NULL WHERE id=? AND claimed_by=? AND status='CLAIMED' RETURNING *",[JSON.stringify(result||{}),completedAt,id,workerId]);return row(q?.[0]?.results?.[0])}
